[package]
name = "agent"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = "0.10"
serde = { version = "1.0", features = ["derive"] }

ic-agent = "0.37.1"
tokio = { version = "1", features = ["full"] }
ic-utils = "0.37.0"
